# Generated by Django 2.0.1 on 2018-03-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0009_auto_20180302_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
