# Generated by Django 2.0.1 on 2018-03-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0010_auto_20180302_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='ik',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='lecturer',
            field=models.ManyToManyField(null=True, related_name='lecturer', to='complaint.Lecturer'),
        ),
    ]
