# Generated by Django 2.0.1 on 2018-03-03 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0011_auto_20180302_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
