# Generated by Django 2.0.1 on 2018-03-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0012_poll_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='ik',
            new_name='pollno',
        ),
    ]
