# Generated by Django 2.0.1 on 2018-03-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0015_lecturer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='user',
        ),
    ]
