# Generated by Django 2.0.1 on 2018-03-03 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0016_remove_lecturer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='pollno',
        ),
        migrations.AddField(
            model_name='poll',
            name='pollno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complaint.Lecturer'),
        ),
    ]
