# Generated by Django 2.0.1 on 2018-03-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0017_auto_20180303_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='pollno',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='pollno',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
