# Generated by Django 2.0.1 on 2018-03-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0018_auto_20180303_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complaintno',
            field=models.CharField(max_length=10),
        ),
    ]
