# Generated by Django 2.0.1 on 2018-03-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0019_auto_20180303_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complaintno',
            field=models.IntegerField(default=0),
        ),
    ]
