# Generated by Django 2.0.1 on 2018-03-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0020_auto_20180303_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
