# Generated by Django 2.0.1 on 2018-03-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0023_poll_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='vote',
        ),
    ]
