# Generated by Django 2.0.1 on 2018-03-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0024_remove_poll_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='tot_vot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='lecturer',
            field=models.ManyToManyField(related_name='lecturer', to='complaint.Lecturer'),
        ),
    ]
