# Generated by Django 2.0.1 on 2018-03-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0025_auto_20180305_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='tot_vot',
        ),
        migrations.AlterField(
            model_name='poll',
            name='lecturer',
            field=models.ManyToManyField(null=True, related_name='lecturer', to='complaint.Lecturer'),
        ),
    ]
