# Generated by Django 2.0.1 on 2018-03-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0026_auto_20180306_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='lecturer',
            field=models.ManyToManyField(related_name='lecturer', to='complaint.Lecturer'),
        ),
    ]
