# Generated by Django 2.0.1 on 2018-03-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0027_auto_20180306_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='category',
            field=models.CharField(choices=[('cse', 'CSE-dept'), ('it', 'It-dept'), ('ece', 'ECE-dept'), ('eee', 'EEE-dept'), ('mech', 'MECH-dept'), ('exam', 'Examination-branch'), ('maintenance', 'MAINTENANCE')], max_length=20, null=True),
        ),
    ]
